title: Akhil Sai Gudala
logo: My_img.jpg
description: Skilled Data Engineer Developer specializing in designing and optimizing ETL processes using Ab Initio and cloud platforms like AWS and Snowflake. I focus on delivering efficient, scalable data integration solutions while ensuring high data quality and performanc
#show_downloads: true
theme: jekyll-theme-minimal
